spring:
  datasource:
    url: "jdbc:postgresql://localhost:54321/postgres"
    username: postgres
    password: test

  jpa:
    show-sql: true

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    auditevents.enabled: true
    prometheus.enabled: true
  # Import Flyway Data
#  flyway:
#    locations: classpath:db/migration,classpath:db/testdata
#    skip-default-callbacks: true

#logging.level:
  #org.springframework.web: DEBUG